### ISSUE TITLE
Disk usage

### ISSUE THREAD

**Issue by RC1140** [Flood-UI/flood#308]
Hi
I think it would be quite beneficial to have a small section on the sidebar with the servers disk stats (Free/Used basically), have started working on this for myself but let me know if there is a specific direction or feature set you think should be included.

Thanks for the awesome project.

**Comment by wopian** [comment]
👍, would let me remove the remaining disk space column and only have that information shown once

**Comment by jfurrow** [comment]
Good idea, and thanks for your willingness to implement this! I haven't put a ton of thought into this, but here's what I would love to see:
1. Flood should read the used/total disk space of all volumes directly from the host, regardless of the host operating system
2. The drives displayed in the sidebar should be configurable in the UI tab of the settings modal (so that a user can hide individual drives as desired)

As for the design itself, I'm still sketching out what that might look like. I'll try to provide a mockup tomorrow or the following day, but I'm open to ideas!

**Comment by jfurrow** [comment]
@RC1140 Here's a quick mockup
<img src="https://cloud.githubusercontent.com/assets/1134755/25261284/1d955042-2606-11e7-86e5-6678276b2325.png" width="240"> <img src="https://cloud.githubusercontent.com/assets/1134755/25261285/1da69f96-2606-11e7-92dd-86f75d7bbc1d.png" width="240">

**Comment by RC1140** [comment]
Wow thanks for that , makes things much easier to build, gonna try and work on it more this weekend been just putting together scafolding atm.

**Comment by Phlooo** [comment]
This mockup is perfect!

A similar bar for CPU load would be cool too :)

**Comment by wopian** [comment]
Considering the remaining disk space got removed entirely by https://github.com/jfurrow/flood/commit/fc2fe936fab2fd0a346a0c5011f09bf9ae2074fe, it's now much needed - as the only way to check atm is by SSHing in or reverting to the parent commit

**Comment by RC1140** [comment]
Whoa , I totally forgot about this work , sorry about the delay , will restart work on this.

**Comment by Soullivaneuh** [comment]
@jfurrow the mock up looks good, but why not putting the disk usage below the speed graph? Make more senses to me.

**Comment by jesec** [comment]
@RC1140 

This feature has been implemented by https://github.com/Flood-UI/flood/pull/808. 

You may close the issue if it is no longer relevant.
