### ISSUE TITLE
npm audit indicates 66 vulns, with 4 high and 2 moderate

### ISSUE THREAD

**Issue by Cubox-** [Flood-UI/flood#787]
npm audit shows:

`found 66 vulnerabilities (60 low, 2 moderate, 4 high) in 37151 scanned packages
  64 vulnerabilities require semver-major dependency updates.
  2 vulnerabilities require manual review. See the full report for details.`

This is after running npm audit fix.
As I am not familiar with npm, or NodeJS, I am unsure how bad it is, but it does not seem sane to keep vulnerable dependencies.

**Comment by jwbuiter** [comment]
Running `npm audit` shows that the vulnerabilities are caused by these packages:
- `jest`: Testing is not yet used, so jest can be safely updated to the recommended version, doing this fixes 60 of the vulnerabilities
- `css-loader`: Updating this to the recommended version introduces the peer dependency `webpack@4.0.0`, which breaks the dev client.
- `node-sass`: The vulnerability is not yet fixed in the latest version of this package
- `webpack-dev-server`: This has the same problem as `css-loader`
- `jsdoc`: The vulnerability is fixed in the github of this package, but the published version on NPM has not been updated in 2 years

**Comment by Cubox-** [comment]
Thanks for the details.
As I am not familiar with node/npm, I just wanted to report what I saw installing flood. A bit scary at first

**Comment by noraj** [comment]
Now that you're question was answered. Thx @jwbuiter
