### ISSUE TITLE
Disable the ability to have different instances of rtorrent tied to different users

### ISSUE THREAD

**Issue by Cubox-** [Flood-UI/flood#791]
Type: Feature Request

- [X] If you want to contribute to the project please review the [contributing guidelines](https://github.com/Flood-UI/flood/blob/master/.github/CONTRIBUTING.md).

## Summary
In my setup, I will only have one instance of rtorrent per flood instance.
It could simplify setup to just give the socket path to flood in the JS configuration, rather than having to have it set per user.

I spent a bit of time figuring out why I could not create an user, before realising I had to enter the rtorrent instance socket path, since I assumed all accounts were tied to the same rtorrent instance

## Idea of implementation
Add an other way to setup flood communication with rtorrent.
Specify the communication path in config.js, making all user use this instance. Disable user's abilities to change this path, or any prompt for it.

**Comment by noraj** [comment]
Please respect issue templates, in your case bug report or feature request.

**Comment by zawapete** [comment]
@Cubox- why do you need different users in the first place if you use only one rtorrent instance?
You can simplify setup creating only one user, since having different users is simply not needed for your use

**Comment by Cubox-** [comment]
> Please respect issue templates, in your case bug report or feature request.

Apologies. Fully updated respecting the template.



> @Cubox- why do you need different users in the first place if you use only one rtorrent instance?
> You can simplify setup creating only one user, since having different users is simply not needed for your use

Two reasons, first I have a secure password for my account, and do not wish to share it with the other human using the instance.
Second, this allows me to have another user, which will not be an admin. I am unsure what an admin can do versus what a non-admin can do in flood, but this allows privilege separation.

**Comment by zawapete** [comment]
@Cubox- sorry to tell you but there's a lot of confusion on security concerns: you don't need multiple users on flood because you are sharing the same rtorrent instance: every user even if it's not admin can do everything (the only difference is that admin can setup and delete other users but not himself)
if you share the same password from your account on flood with other accounts you have that's a wrong choice and bad habit that having one single account would actually solve: so that you'll be forced to not share your password.
if you have one instance you don't need multiple users. if you are worried that you are sharing your password its' because you use one password for everything, and that's nothing about this bad habit other than not sharing one password for everything

if you really need and care for privilige separation you would have separate rtorrent instances and you wouldn't face the problem you think you're facing (that's actually having wrong expectation for the right behaviour)

**Comment by Cubox-** [comment]
Thanks for the reply.

I understand all of that, it's just the way I see things. If I can create multiple users, to me, it means multiple humans users .

Regarding sharing password, while the password is unique to flood, I still do not want to share it with anyone. I have OCD regarding password security, having a shared password between two people is bad.

I can see how my request is not compatible with how flood is build.

**Comment by zawapete** [comment]
they would be multiple human users sharing exactly the same instance with all the same privilige on the same instance: you can still do setting for every user the same conf. you don't really need a feature for this, as I see it

**Comment by Cubox-** [comment]
Yeah, there is no point in requesting this as a feature, thanks for explaining to me. I assumed the admin role limited more than that.
